### ISSUE TITLE
implement RPCh ethers adaptor into BW

### ISSUE THREAD

**Issue by nionis** [Rpc-h/extension-block-wallet#1]
### Description

Blocked by https://github.com/Rpc-h/RPCh/issues/37

Implement RPCh ethers adaptor into Block Wallet.

### Relevant issues

- [x] implement the RPCh ethers adaptor
- [x] adapt RPCh dependencies to be web compatible
- [x] perform testing (using sandbox)

### Definition of DONE

Once RPCh adaptor has been implemented and Block Wallet can use RPCh out of the box.

**Comment by nionis** [comment]
Closed at b0f2cbda6cb981d483f3d4441026a82b438a8bed
