### ISSUE TITLE
BlockWallet + RPCh alpha integration

### ISSUE THREAD

**Issue by nionis** [Rpc-h/extension-block-wallet#7]
- [x] we need to branch off our PR from their beta branch and recreate the PR
- [x] test if `unsafe-wasm` works with manifest v3 (if it runs on chrome it should be ok)
- [x] add new network in `INITIAL_NETWORKS` in `constants.networks` (copy gnosis one)
- [x] initialise provider in `setNetwork` in `NetworkController`
- [x] fix WASM integration to manifest v3
- [x] fix https://github.com/Rpc-h/extension-block-wallet/issues/6

**Comment by diegoalzate** [comment]
@nionis block wallet loads in chrome with `wasm-unsafe-eval` instead of `wasm-eval`

**Comment by nionis** [comment]
Done
